### ISSUE TITLE
Will AADExporter export any sensitive data out of AAD?

### ISSUE THREAD

**Issue by neallee2012** [microsoft/azureadexporter#10]
Hi,

Can we add a statement to address if AADExporter will export any sensitive data out of AAD, such as password, secret, certificate, etc?

Thanks,
Neal

**Comment by astaykov** [comment]
The very first paragraph of the readme addresses that:

> The Azure AD Exporter is a PowerShell module that allows you to export your Azure AD and Azure AD B2C **configuration settings** to local .json files.

It is not by accident that only `configuration settings` is mentioned.

In addition to that, AzureADExporter is based on Microsoft Graph APIs. There are no Graph APIs (and there will not be) that would allow exporting any such sensitive information.

When working with Azure AD, one cannot read any of the following properties/attributes:

 * Password (of User object) - before all, passwords are never stored in clear text
 * Password (also known as secret) of Service Principal / Application object
 * Private Key of any sort of certificate uploaded to Azure AD (e.g. custom signing certificate or certificate credential)
