### ISSUE TITLE
UNable to Connect To MgGraph after installing and importing module

### ISSUE THREAD

**Issue by gouthambaskarn** [microsoft/azureadexporter#17]
I have installed the AzureADExporter module and whenever I try to connect, I get the below response.

I have tried installign the Graph module seperately. I am not able to connect to MgGraph and consequently unable to run the export.

Connect-MgGraph : The term 'Connect-MgGraph' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At C:\Users\CA-D-Win-Admin-17\Documents\WindowsPowerShell\Modules\AzureADExporter\1.0.908740\Connect-AzureADExporter.ps1:20 char:5
+     Connect-MgGraph -TenantId $TenantId -Scopes 'Directory.Read.All',
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-MgGraph:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-MgContext : The term 'Get-MgContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At C:\Users\CA-D-Win-Admin-17\Documents\WindowsPowerShell\Modules\AzureADExporter\1.0.908740\Connect-AzureADExporter.ps1:34 char:5
+     Get-MgContext
+     ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-MgContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-MgContext : The term 'Get-MgContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At C:\Users\CA-D-Win-Admin-17\Documents\WindowsPowerShell\Modules\AzureADExporter\1.0.908740\Connect-AzureADExporter.ps1:35 char:25
+     $global:TenantID = (Get-MgContext).TenantId
+                         ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-MgContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by wipash** [comment]
Try installing the Microsoft Graph PowerShell SDK manually: https://docs.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-beta

**Comment by gouthambaskarn** [comment]
Thanks for responding wipash. I have tried that and in fact I already had MgGraph when i installed the exporter module. Same behavior.

**Comment by merill** [comment]
You can run Get-Module to see a list of the currently loaded modules. If you don't see Microsoft.Graph.Authentication you will need to fix that first. Either with install-module or import-module.

```
❯ Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.9.5                 Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Dis…
Script     1.9.2                 Microsoft.Graph.Identity.Directory… {Complete-MgDirectoryImpactedResource, C…
Script     1.9.2                 Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCreatedObject, Ge…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item,…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, C…
```
