### ISSUE TITLE
Authentication prompt for each and every export step

### ISSUE THREAD

**Issue by LijuV-MSFT** [microsoft/azureadexporter#25]
Is it normal that each and every export steps prompts for authentication, even though I have run the `Connect-AzureADExporter `command, I am running as a Global Administrator, and the user does not need MFA?
![image](https://user-images.githubusercontent.com/47825646/180459648-ed3561f6-1bf8-4f4c-a633-6272687940f2.png)

**Comment by merill** [comment]
This happens when the Graph token cache in your profile is corrupt. 

See the command to clear the profile at https://github.com/microsoftgraph/msgraph-sdk-powershell#known-issues
