### ISSUE TITLE
Question: Why do you recommend emptying the destination folder before running the export?

### ISSUE THREAD

**Issue by SamErde** [microsoft/azureadexporter#32]
I'm curious about the step on [line 191](https://github.com/microsoft/azureadexporter/blob/f685f056702b3418969febdd190efe0a59108a36/README.md#L191) of the readme that removes all items in the target export folder:

```powershell
$tenantPath = './<tenant export path>'
$tenantId = '<tenant id>'
Write-Host 'git checkout main...'
git config --global core.longpaths true #needed for Windows
git checkout main

Write-Host 'Clean git folder...'
Remove-Item $tenantPath -Force -Recurse
```
Is the purpose of this to start with a clean slate, or is it required to prevent issues with git?

**Comment by merill** [comment]
Correct, if items are deleted in the cloud we would have left over items from the previous run being commited.

**Comment by SamErde** [comment]
Thanks, that makes sense!
