### ISSUE TITLE
Listing of valid filters

### ISSUE THREAD

**Issue by DeanGross** [microsoft/azureadexporter#4]
Where can we find a listing of the valid filter values?

**Comment by cblomart** [comment]
Hi Dean,

I just pushed some update to the readme to try and answer your question.

There are two sides to the answer:
* you can select what is exported via the type argument. The current supported types have been added.
* you can alter how filtering is done via a few flags, mostly impacting exporting groups and privilege identity management information.

Please let us know if the changes did address your question,
 
 Cédric

**Comment by DeanGross** [comment]
Looks great, exactly what I was looking for. Thanks for the quick response.  I ran it for everything and it took quite a while, don't think I will do that again:)

**Comment by cblomart** [comment]
Happy to help!
I will proceed to close this issue then.
