### ISSUE TITLE
Use export tool for B2C Tenants via MSI

### ISSUE THREAD

**Issue by paul1384** [microsoft/azureadexporter#44]
Does anyone know if it's possible to use the azureadexporter with an Azure Managed Identity? Ideally would like to set this tool up in an Azure Automation Account to run each day which can login to each B2C tenant and backup all of its settings into a storage account.
I can run the tool manually and get the JSON files out but want to look at automating this instead,

**Comment by merill** [comment]
Yes, you can use Connect-MgGraph -Identity and then run the export.
