### ISSUE TITLE
Recovery Capabilities for Disaster Scenarios

### ISSUE THREAD

**Issue by iflach** [microsoft/azureadexporter#45]
Hello everyone,
 I have a question regarding this project. Once I have exported the Azure AD objects, is there a way to restore or deploy them in the event of a disaster?
 
 Thank you in advance.

**Comment by cblomart** [comment]
Hi @iflach, 

restoring objects to azure ad has different implications (cannot restore with the same id). We made the choice not to propose those as the logic could be complicated and need customisation for many use cases.

By having a history of the configuration we do hope that this project will still help you spot changes and take proper actions to maintain Azure AD configurations.
