### ISSUE TITLE
No data is exported

### ISSUE THREAD

**Issue by ArvoX** [microsoft/azureadexporter#5]
I try to use the tool but the export dir is just empty after each run.
I got some errors but it looks like it is running to completion.

`
PS C:\AzureADBackup> Export-AzureAD -Path 'C:\AzureADBackup\' -All
 Organization/Organization.json
 Organization/Settings.json
 Organization/Branding/Localizations.json
 Organization/CertificateBasedAuthConfiguration.json
 Domains
 Identity/APIConnectors
Export-AzureAD : GET https://graph.microsoft.com/beta/identity/apiConnectors
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 46d1a0a4-c748-4c6f-a0b4-0ad78b041176
client-request-id: 46d1a0a4-c748-4c6f-a0b4-0ad78b041176
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":
"AM4PEPF0000C4CC"}}
Date: Wed, 18 Aug 2021 14:10:33 GMT
Content-Encoding: gzip
Content-Type: application/json
{"error":{"code":"InternalServerError","message":"Unable to find target address","innerError":{"date":"2021-08-18T14:10
:34","request-id":"46d1a0a4-c748-4c6f-a0b4-0ad78b041176","client-request-id":"46d1a0a4-c748-4c6f-a0b4-0ad78b041176"}}}
At line:1 char:1
+ Export-AzureAD -Path 'C:\AzureADBackup\' -All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-AzureAD

 IdentityProviders
 Identity/ContinuousAccessEvaluationPolicy
 SubscribedSkus
 DirectoryRoles
 Identity/B2XUserFlows
 Policies/IdentitySecurityDefaultsEnforcementPolicy
 Policies/AuthorizationPolicy
 Policies/FeatureRolloutPolicies
 Policies/ActivityBasedTimeoutPolicy
 Policies/HomeRealmDiscoveryPolicy
 Policies/ClaimsMappingPolicy
 Policies/TokenIssuancePolicy
 Policies/AuthenticationMethodsPolicy/AuthenticationMethodConfigurations/Email.json
 Policies/AuthenticationMethodsPolicy/AuthenticationMethodConfigurations/FIDO2.json
 Policies/AuthenticationMethodsPolicy/AuthenticationMethodConfigurations/MicrosoftAuthenticator.json
 Policies/AuthenticationMethodsPolicy/AuthenticationMethodConfigurations/SMS.json
 Policies/AuthenticationMethodsPolicy/AuthenticationMethodConfigurations/TemporaryAccessPass.json
 Policies/AdminConsentRequestPolicy
 Policies/PermissionGrantPolicies
 Identity/Conditional/AccessPolicies
 Identity/Conditional/NamedLocations
 IdentityGovernance\EntitlementManagement\AccessPackages
 IdentityGovernance/AccessReviews
 IdentityGovernance/TermsOfUse/Agreements
 IdentityGovernance/EntitlementManagement/ConnectedOrganizations
 IdentityGovernance/EntitlementManagement/Settings
 AdministrativeUnits
 PrivilegedAccess/AADRoles/Resources
 PrivilegedAccess/AzureResources/Resources
Export-AzureAD : GET https://graph.microsoft.com/beta/privilegedAccess/azureResources/resources
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: dc96cfdb-9380-4839-bc63-6860ac4cd350
client-request-id: dc96cfdb-9380-4839-bc63-6860ac4cd350
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":
"AM4PEPF0000DE2B"}}
Date: Wed, 18 Aug 2021 14:11:04 GMT
Content-Encoding: gzip
Content-Type: application/json
{"error":{"code":"InternalServerError","message":"Unable to find target address","innerError":{"date":"2021-08-18T14:11
:04","request-id":"dc96cfdb-9380-4839-bc63-6860ac4cd350","client-request-id":"dc96cfdb-9380-4839-bc63-6860ac4cd350"}}}
At line:1 char:1
+ Export-AzureAD -Path 'C:\AzureADBackup\' -All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-AzureAD

 OnPremisesPublishingProfiles/Provisioning.json
 OnPremisesPublishingProfiles/Provisioning/PublishedResources
 OnPremisesPublishingProfiles/Provisioning/AgentGroups
 OnPremisesPublishingProfiles/Provisioning/Agents
 OnPremisesPublishingProfiles/ApplicationProxy/Connectors
 OnPremisesPublishingProfiles/ApplicationProxy/ConnectorGroups
 Groups
 GroupSettings
 Applications
 ServicePrincipals
 Users
`

**Comment by merill** [comment]
Can you try to run a smaller list? ie without the -All parameter?
