### ISSUE TITLE
Question: How to import

### ISSUE THREAD

**Issue by BurgerhoutJ** [microsoft/azureadexporter#7]
Hi,

I exported the settings, changed a few settings, but how can I import the changes back to Azure AD?

**Comment by merill** [comment]
@BurgerhoutJ thanks for trying out the solution. The intent for this solution was to export your config and data. It can be used to create a historical view of changes over time.
We have intentionally avoided building an import capability to avoid confusing this as a backup/restore option (which it is not). 

The Azure AD product team is working on a native backup/restore capability that will be available out of the box and we didn't want to duplicate that effort.

**Comment by BurgerhoutJ** [comment]
@merill Thanks for the info. 

Do you know what the expectation is that this backup/restore tool will be published?

**Comment by merill** [comment]
Sorry I don't have ETAs on when the native solution will be available.

**Comment by matt-grain** [comment]
Hi @merill, any news on this backup/restore tool?
